name = "astrofinance-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "astrofinance-db"
database_id = "062ee783-b8fd-40a6-b3a9-23a67f5f1497"

[vars]
# Variáveis de ambiente (substituir em produção por valores mais seguros)
JWT_SECRET = "astrofinance-super-secret-key-2024"

# Configurações para ambiente de desenvolvimento
[env.development]
[env.development.vars]
JWT_SECRET = "dev-jwt-secret-for-testing" 